// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZEsPPJIhUSVEdMSL1P5vUihjuuHL1Cag',
    appId: '1:737281591466:web:bcd41cd1bcf00f9421e8d3',
    messagingSenderId: '737281591466',
    projectId: 'task3firebase-dfa9b',
    authDomain: 'task3firebase-dfa9b.firebaseapp.com',
    storageBucket: 'task3firebase-dfa9b.appspot.com',
    measurementId: 'G-WT1GZHSSY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCglxzycfuYDcIPBdD-ovsLohsMgDrU7oc',
    appId: '1:737281591466:android:04ecd42f133a469821e8d3',
    messagingSenderId: '737281591466',
    projectId: 'task3firebase-dfa9b',
    storageBucket: 'task3firebase-dfa9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFucjAA-y2Tjhq0-4YbeEWg5x5Hx3cu10',
    appId: '1:737281591466:ios:eb45d29514864e2821e8d3',
    messagingSenderId: '737281591466',
    projectId: 'task3firebase-dfa9b',
    storageBucket: 'task3firebase-dfa9b.appspot.com',
    iosBundleId: 'com.example.task3Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFucjAA-y2Tjhq0-4YbeEWg5x5Hx3cu10',
    appId: '1:737281591466:ios:9ad418fbf28dafcb21e8d3',
    messagingSenderId: '737281591466',
    projectId: 'task3firebase-dfa9b',
    storageBucket: 'task3firebase-dfa9b.appspot.com',
    iosBundleId: 'com.example.task3Firebase.RunnerTests',
  );
}
